{% set name = "snirf" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snirf-{{ version }}.tar.gz
  sha256: e78f207608b986ab2df773bba3475895a792ee699451423ca5f0cfad50a17b8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - h5py >=3.1.0  # needed for import in setup.py
  run:
    - python >=3.6
    - h5py >=3.1.0
    - numpy
    - setuptools
    - pip
    - termcolor
    - colorama

test:
  imports:
    - snirf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BUNPC/pysnirf2
  summary: Interface and validator for SNIRF files
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
